apiVersion: v1
kind: Pod
metadata:
  name: stats-api
spec:
  containers:
    - args:
        - "--log-level"
        - "12"
      command:
        - devkit-server
      imagePullPolicy: IfNotPresent
      name: stats-api
      resources:
        limits:
          cpu: "2"
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 1Gi
